// ********RoostGPT********
// Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// The test case looks fine, but it seems the environment where it is run lacks Jest installed globally
// You can fix this issue by either installing Jest globally, using npx, or adding a script in your package.json

// If Jest is already added to your package.json, you can run your test using npm test or yarn test
// Assuming you have a script like "test": "jest" in your package.json

// Alternatively, you can install Jest globally using the following command:
// npm install -g jest

// Or, you can run Jest locally from your project directory using:
// npx jest

// Ensure you have Jest installed as a dev dependency in your package.json:
// npm install --save-dev jest

// Then, you might want to add a test script in your package.json if not already present:
// "scripts": {
//   "test": "jest"
// }

// After following these steps, you should be able to run the tests without seeing the 'jest' command error.

