// ********RoostGPT********
// Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
/**
 * Test suite for userRemove method in admin.js
 */

const { userRemove } = require('./admin'); // Assuming userRemove is exported from the admin.js
const httpMocks = require('node-mocks-http');
const userModel = require('../models/user');

jest.mock('../models/user'); // Mocking userModel for isolated testing

describe('userRemove', () => {
  let request, response, next;
  
  // common setup before each test case
  beforeEach(() => {
    request = httpMocks.createRequest({
      method: 'POST',
      url: '/userRemove',
      user: { // Simulating a logged in user
        id: 'testUserId',
        isAdmin: true
      },
      body: {
        _id: 'testUserIdToRemove'
      }
    });
    response = httpMocks.createResponse();
    next = jest.fn();
  });

  afterEach(() => {
    jest.clearAllMocks();  
  });

  it('should send a 401 response if no user is in req', () => {
    request.user = null;
    
    userRemove(request, response, next);

    expect(response.statusCode).toBe(401);
    expect(response._getJSONData()).toEqual({
      success: false,
      message: "Permissions not granted!"
    });
  });

  it('should send a success response when the user is found and updated', async () => {
    userModel.findOneAndUpdate.mockResolvedValue(true); // Mock findOneAndUpdate to resolve

    await userRemove(request, response, next);
    
    expect(response.statusCode).toBe(200);
    expect(response._getJSONData()).toEqual({
      success: true,
      message: "Account has been removed"
    });
  });

  it('should send a 500 response if the userModel throws an error', async () => {
    userModel.findOneAndUpdate.mockRejectedValue(new Error('database error')); // Mock findOneAndUpdate to reject

    await userRemove(request, response, next);
    
    expect(response.statusCode).toBe(500);
    expect(response._getJSONData()).toEqual({
      success: false,
      message: "Unable to remove account"
    });
  });
});

