// ********RoostGPT********
// Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
const server = require('./app');
const { jest } = require('@jest/globals');

describe('Server Startup Test Suite', () => {

  let originalLog;
  let logOutput;

  beforeAll(() => {
    // Capture console logs
    originalLog = console.log;
    logOutput = [];
    console.log = (output) => logOutput.push(output);
  });

  afterAll(() => {
    // Restore console.log
    console.log = originalLog;
  });

  test('Server starts successfully and logs correct listening message', () => {
    const PORT = 3000;
    server.listen = jest.fn().mockImplementation((port, callback) => callback());
    server.listen(PORT, () => {});

    expect(server.listen).toHaveBeenCalledWith(PORT, expect.any(Function));
    expect(logOutput).toContain(`Server Started. Server listening to port ${PORT}`);
  });

  test('Server fails to start and logs an error', () => {
    const PORT = 3000;
    const testError = new Error('Test Error');
    server.listen = jest.fn().mockImplementation((port, callback) => callback(testError));
    server.listen(PORT, () => {});

    expect(server.listen).toHaveBeenCalledWith(PORT, expect.any(Function));
    expect(logOutput).toContain(testError.toString());
  });

});

