// ********RoostGPT********
// Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
const request = require('supertest');
const { app } = require('./app');

test('should return 404 and correct error message for invalid API', async () => {
  const response = await request(app).get('/invalidpath');
  expect(response.status).toBe(404);
  expect(response.body).toHaveProperty('message', 'Invalid API. Use the official documentation to get the list of valid APIS.');
});

