// ********RoostGPT********
// Test generated by RoostGPT for test NodeTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
const request = require('supertest');
const express = require('express');
const path = require('path');

const app = express();

app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, 'public', 'index.html'));
});

describe('GET * route', () => {
  let server;
  
  beforeAll(done => {
    server = app.listen(3000, done);
  });
  
  afterAll(done => {
    server.close(done);
  });
  
  test('It should respond with the index.html file', async () => {
    const res = await request(server).get('/any/path');
    expect(res.statusCode).toBe(200);
    expect(res.type).toBe('text/html');
  });
  
  test('It should handle non-existent paths', async () => {
    const res = await request(server).get('/non-existent/path');
    expect(res.statusCode).toBe(200);
    expect(res.type).toBe('text/html');
  });
  
  test('It should serve the same index.html for different paths', async () => {
    const res1 = await request(server).get('/some/path');
    const res2 = await request(server).get('/another/path');
    
    expect(res1.text).toEqual(res2.text);
    expect(res1.statusCode).toBe(200);
    expect(res2.statusCode).toBe(200);
  });
});

